version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go

  redis:
    image: redis
    ports:
      - "6379:6379"
